### ISSUE TITLE
Firewall starting Error

### ISSUE THREAD

**Issue by BenJule** [tlex/bfs#2]
root@debian7:~# /opt/bfs/bin/start_firewall.sh
Stopping firewall OK
Starting the firewall
Bad argument `123.456.789.123'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `123.456.789.123'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `123.456.789.123'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `123.456.789.123'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `123.456.789.123'
Try `iptables -h' or 'iptables --help' for more information.

**Comment by tlex** [comment]
Can you please send me the content of bfs.firewall.local so I can take a look?

It looks like the iptables commands you've added aren't with the correct iptables sintax.

**Comment by BenJule** [comment]
${IPT} -A INPUT -m state --state NEW -p tcp --dport 32443 -j ${STATS} -m comment --comment "GenStat: Plex"
${IPT} -A INPUT -m state --state NEW -p tcp --dport 32400 -j ${STATS} -m comment --comment "GenStat: Plex"
${IPT} -A INPUT -m state --state NEW -m udp -p udp --dport 32400 -j ${STATS} -m comment --comment "GenStat: Plex" 
${IPT} -A INPUT -m state --state NEW -m udp -p udp --dport 32410 -j ${STATS} -m comment --comment "GenStat: Plex" 
${IPT} -A INPUT -m state --state NEW -m udp -p udp --dport 32412 -j ${STATS} -m comment --comment "GenStat: Plex"
${IPT} -A INPUT -m state --state NEW -m udp -p udp --dport 32414 -j ${STATS} -m comment --comment "GenStat: Plex"
${IPT} -A INPUT -m state --state NEW -p tcp --dport 5055 -j ${STATS} -m comment --comment "GenStat: CouchPotato"
${IPT} -A INPUT -m state --state NEW -p tcp --dport 8118 -j ${STATS} -m comment --comment "GenStat: Deluge Web Daemon"
${IPT} -A INPUT -m state --state NEW -p tcp --dport 18881:18891 -j ${STATS} -m comment --comment "GenStat: Deluge Incoming"
${IPT} -A INPUT -m state --state NEW -p udp --dport 18881:18891 -j ${STATS} -m comment --comment "GenStat: Deluge Incoming"
${IPT} -A INPUT -m state --state NEW -p tcp --dport 8180 -j ${STATS} -m comment --comment "GenStat: SickBeard"
${IPT} -A INPUT -p udp -i ${PUBIF} --dport 137 -j ${DSTATS} -m comment --comment "SMB Protocol"
${IPT} -A INPUT -p udp -i ${PUBIF} --dport 138 -j ${DSTATS} -m comment --comment "SMB Protocol"
${IPT} -A INPUT -p udp -i ${PUBIF} --dport 67 -j ${DSTATS} -m comment --comment "DHCP"
${IPT} -A INPUT -p udp -i ${PUBIF} --dport 1900 -j ${DSTATS} -m comment --comment "Microsoft SSDP Enables discovery of UPnP devices"
${IPT} -A INPUT -d 224.0.0.0/255.255.255.0 -j ${DSTATS} -m comment --comment "Multicast"

**Comment by tlex** [comment]
I'll build in a few logging hooks to see where the script has an error.

**Comment by BenJule** [comment]
thank you

**Comment by tlex** [comment]
Ok, turns out that the IP adress is not correctly parsed once you have multiple IPs on the same interface. I suggest as workaround to add one IP manually in bfs.conf (in bfs.conf.example it would mean commenting out line 78 and using the format on line 79) until i get around to implement #1
