### ISSUE TITLE
results are sliced * like yellow mark

### ISSUE THREAD

**Issue by BenJule** [tlex/bfs#3]
![unbenannt](https://cloud.githubusercontent.com/assets/7575797/6485726/f2bd4aea-c285-11e4-9c74-c9275809cdd7.PNG)

**Comment by tlex** [comment]
Labeled it as bug, even though I see it as a compatibility issue between highcharts (www.highcharts.com) and firefox. Fixed by increasing the margin from 5px to 10px when initializing highcharts.
